# @package _global_

defaults:
  - clean
  - _self_

prep:
  musan_mix:
    volume_variation:
      enabled: true
      low_gain_db: -12.0
      high_gain_db: 6.0
      segment_ms_min: 250.0
      segment_ms_max: 750.0
      transition_ms: 50.0
