defaults:
  - paths: default
  - tokenizer: default
  - training: default
  - fbank: default
  - stage1: default
  - stage2: default
  - phoneme_adapter: default
  - demo: default
  - run: default
  - prep: default
  - adapt: default
  - locator: phoneme_ctc
  - _self_

hydra:
  job:
    chdir: false
